# Задача
* Изучить данные, разбить доноров на группы.
* Постараться предугадать дальнейший возможный трек жертвователя для активных доноров (предпочтительно для тех, с кем есть каналы связи)
* Представить заказчику методику того, как он сможет делать это самостоятельно на обновляющихся данных.

# Заказчик

Благотворительный фонд [«Бюро добрых дел»](https://burodd.ru)

## 1. Загрузка и знакомство с данными

In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import datetime as dt
from plotly import graph_objects as go
import math as mth
from scipy import stats as st

import warnings
warnings.filterwarnings("ignore")

In [ ]:
donors = pd.read_csv('https://docs.google.com/spreadsheets/d/' + 
                   '1LyXy8qjuofwSgEnOrL2fTABlPIU-kaUEzsZtvHCTHJY' +
                   '/export?gid=494519301&format=csv',
                  )
donors.head(5)

,ID,Пол,Город,Дата последней email активности
0,AF575B85-917F-475D-8875-00055586E05B,NaN,NaN,NaN
1,229A9B43-3A15-4A48-8CB6-000EDB240D50,NaN,NaN,NaN
2,C6606486-05A8-4437-ACF9-00344E54FEE1,NaN,NaN,NaN
3,6ED86154-A688-4A11-868F-006209035413,Женский ...,NaN,NaN
4,46C41E20-EA56-4698-9C37-00692FD6FFE8,Женский ...,NaN,NaN

In [ ]:
donations = pd.read_csv('https://docs.google.com/spreadsheets/d/' + 
                   '1LyXy8qjuofwSgEnOrL2fTABlPIU-kaUEzsZtvHCTHJY' +
                   '/export?gid=1916157421&format=csv',
                  )
donations.head(5)

,Donor ID,Дата платежа,Сумма платежа,Рекуррентный,Назначение платежа,Канал оплаты
0,DE5393F9-9585-4057-B7FB-24B69697FC08,7/3/22 19:49,300,Да ...,ПОЖЕРТВОВАНИЕ undefined,Банковские карты
1,81CD4BEF-443E-4D36-B34F-664E11182D65,3/14/20 12:20,300,Нет ...,SMS bdd,SMS
2,D3BEB76D-D8B6-47E2-8109-44F1B278943B,4/7/22 0:00,16,Нет ...,Добровольное пожертвование. НДС не облагается,Прямые поступления на счет
3,F1310736-B229-4AAC-99B7-F13ACECF67CB,12/26/19 2:25,300,Нет ...,NaN,SMS
4,61C3D86B-39DA-445C-9D7F-9924CE9BDA14,6/26/21 1:26,200,Да ...,ПОЖЕРТВОВАНИЕ undefined,Банковские карты

In [ ]:
donors.columns = ['donor_id', 'gender', 'city', 'last_activ']